### PR TITLE
update html5ever

### PR DESCRIPTION
**Pull request by chrunchyjesus**

### CODE REVIEW

**Comment by jugglerchris** [comment]
Thank you!

**Comment by jugglerchris** [comment]
Would it be useful to you for me to do a release with this change soon?

**Comment by chrunchyjesus** [comment]
After #22. 😉

**Comment by jugglerchris** [comment]
Ok, I've published 0.1.12.

**Comment by chrunchyjesus** [comment]
Awesome. Thanks. :+1:

**Pull request merged**
